from linecache import getline

# output file in .inp format
f = open("new1.inp", "w")
f.write(
    """**           ABAQUS Input Deck Generated by HyperMesh Version  : 2021.0.0.33
**           Generated using HyperMesh-Abaqus Template Version : 2021.0.0.33
**           Generated on 09-27-2021 at 12:35:13
**
**             Template:  ABAQUS/EXPLICIT
**
*Heading
** Job name: Job-2 Model name: dummy
** Generated by: Abaqus/CAE 2020
*Preprint, echo=NO, model=NO, history=NO, contact=NO
**
** PARTS
**
*Part, name=PART-1
*Node\n"""
)

# number of nodes
n_nodes = int(getline("new1.mesh", 4))

# read nodes from the file
nodes = []
for i in range(5, 5 + n_nodes):
    nodes.append(getline("new1.mesh", i))

# write nodes to the input file
count = 1
for j in nodes:
    k = j.split()
    f.write(f"{count}, {k[0]}, {k[1]}, {k[2]} \n")
    count = count + 1

f.write("*ELEMENT, TYPE=CPE4R\n")
# read and write 2d elements
lineno = int(n_nodes + 6)
n_quads = int(getline("new1.mesh", lineno))

quads = []
for i in range(7 + n_nodes, 7 + n_nodes + n_quads):
    quads.append(getline("new1.mesh", i))

count = 1
for j in quads:
    k = j.split()
    f.write(f"{count}, {k[0]}, {k[1]}, {k[2]}, {k[3]} \n")
    count = count + 1
f.write("*ELEMENT, TYPE=C3D8R\n")
# read and write 3d elements
lineno = 7 + n_nodes + n_quads + 1
n_hexas = int(getline("new1.mesh", lineno))
print(n_hexas)

hexas = []
for i in range(lineno + 1, lineno + n_hexas + 1):
    hexas.append(getline("new1.mesh", i))

for j in hexas:
    k = j.split()
    f.write(
        f"{count}, {k[0]}, {k[1]}, {k[2]}, {k[3]}, {k[4]}, {k[5]}, {k[6]}, {k[7]}\n"
    )
    count = count + 1

breakpoint()


"""
Copyright 2023 Sandia National Laboratories

Notice: This computer software was prepared by National Technology and Engineering Solutions of
Sandia, LLC, hereinafter the Contractor, under Contract DE-NA0003525 with the Department of Energy
(DOE). All rights in the computer software are reserved by DOE on behalf of the United States
Government and the Contractor as provided in the Contract. You are authorized to use this computer
software for Governmental purposes but it is not to be released or distributed to the public.
NEITHER THE U.S. GOVERNMENT NOR THE CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES
ANY LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this sentence must appear on any
copies of this computer software. Export of this data may require a license from the United States
Government.
"""
