from linecache import getline

# output file in .inp format
f1 = open("bunny.inp", "w")
f1.write(
    """**           ABAQUS Input Deck Generated by HyperMesh Version  : 2021.0.0.33
**           Generated using HyperMesh-Abaqus Template Version : 2021.0.0.33
**           Generated on 09-27-2021 at 12:35:13
**
**             Template:  ABAQUS/EXPLICIT
**
*Heading
** Job name: Job-2 Model name: dummy
** Generated by: Abaqus/CAE 2020
*Preprint, echo=NO, model=NO, history=NO, contact=NO
**
** PARTS
**
*Part, name=PART-1
*Node\n"""
)

# number of nodes
n_nodes = int(getline("bunny.mesh", 4))

print(n_nodes)

# read nodes from the file
nodes = []
for i in range(5, 5 + n_nodes):
    nodes.append(getline("bunny.mesh", i))


# write nodes to the input file
count = 1
for j in nodes:
    k = j.split()
    f1.write(f"{count}, {k[0]}, {k[1]}, {k[2]} \n")
    count = count + 1


f1.write("*ELEMENT, TYPE=C3D8R\n")

# read and write 3d elements
lineno = int(n_nodes + 6)
n_hexas = int(getline("bunny.mesh", lineno))
print(n_hexas)

hexas = []
for i in range(lineno + 1, lineno + n_hexas + 1):
    hexas.append(getline("bunny.mesh", i))

for j in hexas:
    k = j.split()
    f1.write(
        f"{count}, {k[0]}, {k[1]}, {k[2]}, {k[3]}, {k[4]}, {k[5]}, {k[6]}, {k[7]}\n"
    )
    count = count + 1
